### ISSUE TITLE
Add output

### ISSUE THREAD

**Issue by engineerbaz** [engineerbaz/DevOps-08-TrainingCourse#1]
@MuhammadJahangirDevOps Please add output

**Comment by usmanbatch8** [comment]
Add Me, this Batch and follow me

**Comment by usmanbatch8** [comment]
Dear Sir,

Alhamdulillah's! Sir your way of teaching is very great, and i learnt more new Knowledge of GitHub, and Gitbash, but I feel some difficulty roout user switch, further all are Good.

Best of luck for new coming time.

regards,

Muhammad Usman

**Comment by engineerbaz** [comment]
Walikumasalam
You are welcome and thanks for the kind words you have just mentioned. 

please do let me know about switching user the command is very simple Su -

**Comment by engineerbaz** [comment]
> Walikumasalam You are welcome and thanks for the kind words you have just mentioned.
> 
> please do let me know about switching user the command is very simple Su -

@usmanbatch8 please respond back

**Comment by Devops-MJZ** [comment]
issue solved @engineerbaz
