### ISSUE TITLE
For Linux-Assignment-01.md

### ISSUE THREAD

**Issue by mmujtababashir** [engineerbaz/DevOps-08-TrainingCourse#4]
For assignment Linux-Assignment-01.md didn't get 2nd portion of task #4. Kindly share the details

**Comment by usmanbatch8** [comment]
I have shared all Assignments on GitHub

**Comment by engineerbaz** [comment]
Just write about any 5 Commands briefly like 'ls' is for listing @mmujtababashir

**Comment by engineerbaz** [comment]
@usmanbatch8 can you share link please , I Cant see your folder
