### ISSUE TITLE
Merging issue

### ISSUE THREAD

**Issue by Kanwal243** [engineerbaz/DevOps-08-TrainingCourse#5]
@engineerbaz Kindly check while pushing .

**Comment by engineerbaz** [comment]
What you are pushing ? Pl share details @Kanwal243

**Comment by Kanwal243** [comment]
![merge](https://user-images.githubusercontent.com/83213183/225860592-0711356d-87e7-4a5c-8497-8cd6d7024024.PNG)

Linux Assignment file.

**Comment by usmanbatch8** [comment]
Mrs, Kanwal What is this? Is this simple Text.

**Comment by Kanwal243** [comment]
nope.. it's an png images.
